
# This workflow generates the changelog file in the
# documentation based on the merged pull requests
# See more at: https://github.com/heinrichreimer/action-github-changelog-generator

name: Changelog Generator

on:
  push:
    branches: [ master ]

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install github_changelog_generator
      run: gem install github_changelog_generator
      
    - name: Gen changelog
      run: github_changelog_generator -t ${{ secrets.CHANGELOG_TOKEN }} -u casbin -p casbin-rs
      
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Changelog
        file_pattern: CHANGELOG.md
